package server

import (
	"context"
	"fmt"
	"log"
	"net"

	"google.golang.org/grpc"

	// Adjust the import path based on your module path

	"github.com/Networks-it-uc3m/l2sm-switch/internal/controller"

	plsv1 "github.com/Networks-it-uc3m/l2sm-switch/api/v1"
	dp "github.com/Networks-it-uc3m/l2sm-switch/pkg/datapath"
	"github.com/Networks-it-uc3m/l2sm-switch/pkg/nedpb"
)

// server is used to implement nedpb.VxlanServiceServer
type server struct {
	nedpb.UnimplementedNedServiceServer
	Ctr *controller.Controller
}

func StartGrpcServer(port string, ctr *controller.Controller) {

	// Listen on a TCP port
	lis, err := net.Listen("tcp", fmt.Sprintf(":%s", port)) // Choose your port
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	// Create a gRPC server
	grpcServer := grpc.NewServer()

	// Register the server
	nedpb.RegisterNedServiceServer(grpcServer, &server{Ctr: ctr})

	log.Printf("gRPC server listening on :%s", port)
	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}

// CreateVxlan implements nedpb.VxlanServiceServer
func (s *server) CreateVxlan(ctx context.Context, req *nedpb.CreateVxlanRequest) (*nedpb.CreateVxlanResponse, error) {
	ipAddress := req.GetIpAddress()

	// Implement your logic to create a VxLAN with the given IP address
	// For example, call a function from pkg/ovs/vsctl.go
	// success, message := ovs.CreateVxlan(ipAddress)
	//TODO: finish. its required to disclose what happens if i dont know the number of vxlans --- vxlan name generated by ovs pkg?
	// Placeholder implementation
	s.Ctr.ConnectNewNeighbor(ipAddress)
	message := fmt.Sprintf("VxLAN with IP %s created successfully", ipAddress)

	return &nedpb.CreateVxlanResponse{
		Success: false,
		Message: message,
	}, nil
}

// AttachInterface implements nedpb.VxlanServiceServer
func (s *server) AttachInterface(ctx context.Context, req *nedpb.AttachInterfaceRequest) (*nedpb.AttachInterfaceResponse, error) {

	ifid := dp.New(s.Ctr.GetSwitchName())

	p, err := s.Ctr.GetNewPort(ifid)
	if err != nil {
		return nil, fmt.Errorf("failed to generate a new port name. error: %v", err)
	}
	//todo: new port must be created!!!
	err = s.Ctr.AddPorts([]plsv1.Port{p})

	if err != nil {
		return nil, fmt.Errorf("failed to add interface to bridge: %v", err)
	}

	return &nedpb.AttachInterfaceResponse{
		InterfaceNum: int64(*p.Id),
		NodeName:     s.Ctr.GetNodeName(),
	}, nil
}
